#!/bin/bash
#
# tinc                  tincd VPN setup
#
# chkconfig:    2345 10 90
#
# version:      1.0.0
# author:       logos <Logos01 @ irc.freenode.net >
#
#
# Source function library
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "x${NETWORKING}" = "xno" ] && exit 0

VPN_NAME="<<PUT_A_VPN_NAME_HERE>>"

TINCD_EXEC="/usr/sbin/tincd"
TINCD_CONF="/etc/tinc/${VPN_NAME}"
TINCD_PID="/var/run/tinc_${VPN_NAME}.pid"
DEBUG=""
#DEBUG="-d3"

alias tincd="${TINCD_EXEC}"

#Check for executable
if [ ! -x ${TINCD_EXEC} ] ; then
    echo "**tinc: tincd does not exist or is not executable!" >&2
fi

_start() {
    tincd -n "${VPN_NAME}" ${DEBUG} --pidfile="${TINCD_PID}"
}

_stop() {
    tincd -n ${VPN_NAME} -k --pidfile="${TINCD_PID}"
}

_restart() {
    _stop;
    sleep 0.5
    _start
}

_reload() {
    tincd -n "${VPN_NAME}" --kill=HUP --pidfile="${TINCD_PID}"
}

_status() {
    current_pid=$(/usr/bin/pgrep -f "${TINCD_EXEC} -n ${VPN_NAME}")
    if [ "${current_pid}"] ; then
        /usr/sbin/lsof -p "${current_pid}" | grep TCP
    else
        echo "tincd_${VPN_NAME} is not currently running."
    fi
}




case "$1" in
    start)
        _start
        ;;
    stop)
        _stop
        ;;
    reload)
        _reload
        ;;
    restart)
        _restart
        ;;
    reload)
        _reload
        ;;
    status)
        _status
        ;;
    *)
        echo "Usage: service tincd_${VPN_NAME} {start|stop|reload|restart|status)"
        exit 1
esac

exit 0
